#!/usr/bin/bash

#>........................................

#Colors
NC='\033[0m'        #Default
BD='\033[1m'        #Bold
BL='\033[1;90m'     # Black
R='\033[1;91m'      # Red
G='\033[1;92m'      # Green
Y='\033[1;93m'      # Yellow
B='\033[1;94m'      # Blue
P='\033[1;95m'      # Purple
C='\033[1;96m'      # Cyan
W='\033[1;97m'      # White

#>.........................................

#Effects
E0='lolcat  -F 2 -a -t -d 1 -s 500'
E1='lolcat -a -t -d 1 -s 500'

#>.........................................

t-banner() {
clear;
printf "
 _______         _______  _______  __    _  __    _  _______  ________  
|       |       |  _    ||   _   ||  |  | ||  |  | ||       ||    _   | 
|_     _| ____  | |_|   ||  |_|  ||   |_| ||   |_| ||    ___||   | |  | 
  |   |  |____| |       ||       ||       ||       ||   |___ |   |_|  | 
  |   |         |  _   | |       ||  _    ||  _    ||    ___||    __   |
  |   |         | |_|   ||   _   || | |   || | |   ||   |___ |   |  |  |
  |___|         |_______||__| |__||_|  |__||_|  |__||_______||___|  |__|

"
}

#>.........................................

reqirements() {
if [ ! -f /data/data/com.termux/files/usr/share/figlet/'Shadow S.flf' ];then
echo -ne "\e[0m[⬇] Installing Reqirements & FONTS... \r"
command -v tput > /dev/null 2>&1 || { apt install ncurses-utils &> /dev/null ; connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m[\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi; }
tput civis
command -v figlet > /dev/null 2>&1 || { pkg install figlet -y &> /dev/null ; connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m[\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi; }

command -v ruby > /dev/null 2>&1 || { pkg install ruby -y &> /dev/null ; connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m[\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi; }

command -v lolcat > /dev/null 2>&1 || { pkg install lolcat &> /dev/null ; connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m[\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi; }

#checking connection
connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m[\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi

#main progress
cd $PREFIX/share
git clone https://github.com/abhackerofficial/FONTS-F > /dev/null 2>&1
cd FONTS-F
rm setup && rm LICENSE && rm README.md
mv * $PREFIX/share/figlet
cd $HOME
rm -rf $PREFIX/share/FONTS-F
echo -ne "[√] Reqirements & FONTS Installed         \r"
sleep 1
echo -ne "                                          \r"
tput cnorm
fi
}

#>.........................................

options() {
if [ -f /data/data/com.termux/files/usr/share/figlet/'Shadow S.flf' ];then
printf "Enter a Text Here > "
read input
if [[ $input = "kill" ]] || [[ $input = "exit" ]] || [[ $input = "Kill" ]] || [[ $input = "Exit" ]] || [[ $input = "KILL" ]] || [[ $input = "EXIT" ]]; then
echo -e "\e[91mAbort.\e[0m\n" ; exit 0

elif [[ $input = "reset" ]] || [[ $input = "Reset" ]] || [[ $input = "RESET" ]]; then
clear ; termux-reload-settings ; printf "$NC" ; t-banner ; printf "$NC" ; options

elif [[ $input = "black" ]] || [[ $input = "Black" ]] || [[ $input = "BLACK" ]]; then
clear ; printf "$BD$BL" ; t-banner ; printf "$BD$BL" ; options

elif [[ $input = "red" ]] || [[ $input = "Red" ]] || [[ $input = "RED" ]]; then
clear ; printf "$BD$R" ; t-banner ; printf "$BD$R" ; options

elif [[ $input = "green" ]] || [[ $input = "Green" ]] || [[ $input = "GREEN" ]]; then
clear ; printf "$BD$G" ; t-banner ; printf "$BD$G" ; options

elif [[ $input = "yellow" ]] || [[ $input = "Yellow" ]] || [[ $input = "YELLOW" ]]; then
clear ; printf "$BD$Y" ; t-banner ; printf "$BD$Y" ; options

elif [[ $input = "blue" ]] || [[ $input = "Blue" ]] || [[ $input = "BLUE" ]]; then
clear ; printf "$BD$B" ; t-banner ; printf "$BD$B" ; options

elif [[ $input = "pink" ]] || [[ $input = "Pink" ]] || [[ $input = "PINK" ]]; then
clear ; printf "$BD$P" ; t-banner ; printf "$BD$P" ; options

elif [[ $input = "clay" ]] || [[ $input = "Clay" ]] || [[ $input = "CLAY" ]]; then
clear ; printf "$BD$C" ; t-banner ; printf "$BD$C" ; options

elif [[ $input = "white" ]] || [[ $input = "White" ]] || [[ $input = "WHITE" ]]; then
clear ; printf "$BD$W" ; t-banner ; printf "$BD$W" ; options

elif [[ $input = "rgb" ]] || [[ $input = "Rgb" ]] || [[ $input = "RGB" ]]; then
clear ; printf "$BD" ; t-banner | $E1 ; printf "$BD" ; options | $E1

elif [[ $input = "srgb" ]] || [[ $input = "Srgb" ]] || [[ $input = "SRGB" ]]; then
clear ; printf "$BD" ; t-banner | $E0 ; printf "$BD" ; options | $E0


else echo;echo
figlet -f "3D Diagonal" "$input"
figlet -f '3-D' "$input"
figlet -f 'Alpha' "'$input'"
figlet -f 'Acrobatic' "$input"
figlet -f 'Avatar' "$input"
figlet -f 'Big Money-ne' "$input"
figlet -f 'Big Money-nw' "$input"
figlet -f 'Big Money-se' "$input"
figlet -f 'Big Money-sw' "$input"
figlet -f 'Big' "$input"
figlet -f 'Blocks' "$input";echo
figlet -f 'Bulbhead' "$input";echo
figlet -f 'Cards' "$input"
figlet -f 'Chiseled' "$input"
figlet -f 'Crawford2' "$input"
figlet -f 'Crazy' "$input"
figlet -f 'Dancing Font' "$input"
figlet -f 'Doh' "$input"
figlet -f 'Doom' "$input"
figlet -f 'Efti Wall' "$input";echo
figlet -f 'Epic' "$input"
figlet -f 'Fire Font-k' "$input"
figlet -f 'Fire Font-s' "$input"
figlet -f 'Flower Power' "$input";echo
figlet -f 'Fun Face' "$input";echo
figlet -f 'Fun Faces' "$input";echo
figlet -f 'Ghost' "$input";echo
figlet -f 'Graceful' "$input";echo
figlet -f 'Graffiti' "$input";echo
figlet -f 'Impossible' "$input";echo
figlet -f 'Isometric1' "$input";echo
figlet -f 'Isometric2' "$input";echo
figlet -f 'Isometric3' "$input";echo
figlet -f 'Isometric4' "$input";echo
figlet -f 'JS Bracket Letters' "$input";echo
figlet -f 'Lil Devil' "$input";echo
figlet -f 'Merlin1' "$input"
figlet -f 'Modular' "$input"
figlet -f 'Ogre' "$input"
figlet -f "Patorjk's Cheese" "$input"
figlet -f 'Patorjk-HeX' "$input"
figlet -f 'Rectangles' "$input"
figlet -f 'Slant' "$input"
figlet -f 'Slant Relief' "$input"
figlet -f 'Small' "$input"
figlet -f 'Small Slant' "$input"
figlet -f 'Small Isometric1' "$input"
figlet -f 'Soft' "$input"
figlet -f 'Standard' "$input"
figlet -f 'Star Wars' "$input"
figlet -f 'Sub-Zero' "$input"
figlet -f 'Swamp Land' "$input"
figlet -f 'Sweet' "$input"
figlet -f 'Train' "$input"
figlet -f 'Twisted' "$input"
figlet -f 'Wet Letter' "$input"
figlet -f 'Varsity' "$input"
figlet -f '3D-ASCII' "$input"
figlet -f 'Shadow R' "'$input'"
figlet -f 'Shadow S' "'$input'"
figlet -f 'Bloody' "$input";echo
figlet -f 'Calvin S' "'$input'";echo
figlet -f 'Delta Corps Priest 1' "$input"
figlet -f 'Electronic' "$input"
figlet -f 'Elite' "$input"
figlet -f 'Stronger Than All' "$input";echo
figlet -f 'THIS' "$input";echo
figlet -f 'The Edge' "$input";echo
figlet -f '1Row' "$input"
figlet -f '3-D' "$input";echo
figlet -f '3x5' "$input";echo
figlet -f '4Max' "$input";echo
figlet -f '5 Line Oblique' "$input"
figlet -f 'AMC 3 Line' "$input"
figlet -f 'AMC 3 Liv1' "$input"
figlet -f 'AMC AAA01' "$input"
figlet -f 'AMC Neko' "$input"
figlet -f 'AMC Razor' "$input"
figlet -f 'AMC Razor2' "$input"
figlet -f 'AMC Slash' "$input"
figlet -f 'AMC Slider' "$input"
figlet -f 'AMC Thin' "$input"
figlet -f 'AMC Tubes' "$input"
figlet -f 'AMC Untitled' "$input"
figlet -f 'ASCII New Roman' "$input"
figlet -f 'Alligator' "$input"
figlet -f 'Alligator2' "$input"
figlet -f 'Alphabet' "$input"
figlet -f 'Arrows' "$input"
figlet -f 'Banner' "$input"
figlet -f 'Banner3-D' "$input"
figlet -f 'Banner3' "$input"
figlet -f 'Banner4' "$input"
figlet -f 'Barbwire' "$input"
figlet -f 'Basic' "$input"
figlet -f 'Bear' "$input"
figlet -f 'Bell' "$input"
figlet -f 'Benjamin' "$input"
figlet -f 'Big Chief' "$input"
figlet -f 'Bigfig' "$input"
figlet -f 'Binary' "$input"
figlet -f 'Block' "$input"
figlet -f 'Bolger' "$input"
figlet -f 'Braced' "$input"
figlet -f 'Bright' "$input"
figlet -f 'Broadway KB' "$input"
figlet -f 'Broadway' "$input"
figlet -f 'Bubble' "$input"
figlet -f 'Caligraphy' "$input"
figlet -f 'Caligraphy2' "$input"
figlet -f 'Catwalk' "$input"
figlet -f 'Chunky' "$input"
figlet -f 'Coinstak' "$input"
figlet -f 'Cola' "$input"
figlet -f 'Colossal' "$input"
figlet -f 'Computer' "$input"
figlet -f 'Contessa' "$input"
figlet -f 'Contrast' "$input"
figlet -f 'Cosmike' "$input"
figlet -f 'Crawford' "$input"
figlet -f 'Cricket' "$input"
figlet -f 'Cursive' "$input"
figlet -f 'Cyberlarge' "$input"
figlet -f 'Cybermedium' "$input"
figlet -f 'Cybersmall' "$input"
figlet -f 'Cygnet' "$input"
figlet -f 'DANC4' "$input"
figlet -f 'DWhistled' "$input"
figlet -f 'Decimal' "$input"
figlet -f 'Def Leppard' "$input"
figlet -f 'Diamond' "$input"
figlet -f 'Diet Cola' "$input"
figlet -f 'Digital' "$input"
figlet -f 'Dot Matrix' "$input"
figlet -f 'Double Shorts' "$input"
figlet -f 'Double' "$input"

printf "[?] Do You Want to Load All Fonts [Y/n] ? "
read out
if [[ $out = "y" ]] || [[ $out = "Y" ]]; then
clear

figlet -f 'Dr Pepper' "$input"
figlet -f 'Efti Chess' "$input"
figlet -f 'Efti Font' "$input"
figlet -f 'Efti Italic' "$input"
figlet -f 'Efti Piti' "$input"
figlet -f 'Efti Robot' "$input"
figlet -f 'Efti Water' "$input"
figlet -f 'Fender' "$input"
figlet -f 'Filter' "$input"
figlet -f 'Flipped' "$input"
figlet -f 'Four Tops' "$input"
figlet -f 'Fraktur' "$input"
figlet -f 'Fuzzy' "$input"
figlet -f 'Georgi16' "$input"
figlet -f 'Georgia11' "$input"
figlet -f 'Ghoulish' "$input"
figlet -f 'Glenyn' "$input"
figlet -f 'Goofy' "$input"
figlet -f 'Gothic' "$input"
figlet -f 'Gradient' "$input"
figlet -f 'Greek' "$input"
figlet -f 'Heart Left' "$input"
figlet -f 'Heart Right' "$input"
figlet -f 'Henry 3D' "$input"
figlet -f 'Hex' "$input"
figlet -f 'Hieroglyphs' "$input"
figlet -f 'Hollywood' "$input"
figlet -f 'Horizontal Left' "$input"
figlet -f 'Horizontal Right' "$input"
figlet -f 'ICL-1900' "$input"
figlet -f 'Invita' "$input"
figlet -f 'Italic' "$input"
figlet -f 'Ivrit' "$input"
figlet -f 'JS Block Letters' "$input"
figlet -f 'JS Capital Curves' "$input"
figlet -f 'JS Cursive' "$input"
figlet -f 'JS Stick Letters' "$input"
figlet -f 'Jacky' "$input"
figlet -f 'Jazmine' "$input"
figlet -f 'Jerusalem' "$input"
figlet -f 'Katakana' "$input"
figlet -f 'Kban' "$input"
figlet -f 'Keyboard' "$input"
figlet -f 'Knob' "$input"
figlet -f 'LCD' "$input"
figlet -f 'Larry 3D' "$input"
figlet -f 'Lean' "$input"
figlet -f 'Letters' "$input"
figlet -f 'Line Blocks' "$input"
figlet -f 'Linux' "$input"
figlet -f 'Lockergnome' "$input"
figlet -f 'Madrid' "$input"
figlet -f 'Marquee' "$input"
figlet -f 'Maxfour' "$input"
figlet -f 'Merlin2' "$input"
figlet -f 'Mike' "$input"
figlet -f 'Mini' "$input"
figlet -f 'Mirror' "$input"
figlet -f 'Mnemonic' "$input"
figlet -f 'Morse' "$input"
figlet -f 'Moscow' "$input"
figlet -f 'Mshebrew210' "$input"
figlet -f 'Muzzle' "$input"
figlet -f 'NScript' "$input"
figlet -f 'NT Greek' "$input"
figlet -f 'NV Script' "$input"
figlet -f 'Nancyj-Fancy' "$input"
figlet -f 'Nancyj-Underlined' "$input"
figlet -f 'Nancyj' "$input"
figlet -f 'Nipples' "$input"
figlet -f 'OS2' "$input"
figlet -f 'Octal' "$input"
figlet -f 'Old Banner' "$input"
figlet -f 'Pawp' "$input"
figlet -f 'Peaks Slant' "$input"
figlet -f 'Peaks' "$input"
figlet -f 'Pebbles' "$input"
figlet -f 'Pepper' "$input"
figlet -f 'Poison' "$input"
figlet -f 'Puffy' "$input"
figlet -f 'Puzzle' "$input"
figlet -f 'Pyramid' "$input"
figlet -f 'Rammstein' "$input"
figlet -f 'Relief' "$input"
figlet -f 'Relief2' "$input"
figlet -f 'Reverse' "$input"
figlet -f 'Roman' "$input"
figlet -f 'Rotated' "$input"
figlet -f 'Rounded' "$input"
figlet -f 'Rowan Cap' "$input"
figlet -f 'Rozzo' "$input"
figlet -f 'Runic' "$input"
figlet -f 'Runyc' "$input"
figlet -f 'S Blood' "$input"
figlet -f 'SL Script' "$input"
figlet -f 'Santa Clara' "$input"
figlet -f 'Script' "$input"
figlet -f 'Serifcap' "$input"
figlet -f 'Shadow' "$input"
figlet -f 'Shimrod' "$input"
figlet -f 'Short' "$input"
figlet -f 'Slide' "$input"
figlet -f 'Small Caps' "$input"
figlet -f 'Small Keyboard' "$input"
figlet -f 'Small Poison' "$input"
figlet -f 'Small Script' "$input"
figlet -f 'Small Shadow' "$input"
figlet -f 'Small Tengwar' "$input"
figlet -f 'Speed' "$input"
figlet -f 'Spliff' "$input"
figlet -f 'Stacey' "$input"
figlet -f 'Stampate' "$input"
figlet -f 'Stampatello' "$input"
figlet -f 'Star Strips' "$input"
figlet -f 'Stellar' "$input"
figlet -f 'Stick Letters' "$input"
figlet -f 'Stop' "$input"
figlet -f 'Straight' "$input"
figlet -f 'Swan' "$input"
figlet -f 'Tanja' "$input"
figlet -f 'Tengwar' "$input"
figlet -f 'Term' "$input"
figlet -f 'Test1' "$input"
figlet -f 'Thick' "$input"
figlet -f 'Thin' "$input"
figlet -f 'Thorned' "$input"
figlet -f 'Three Point' "$input"
figlet -f 'Ticks Slant' "$input"
figlet -f 'Ticks' "$input"
figlet -f 'Tiles' "$input"
figlet -f 'Tinker-Toy' "$input"
figlet -f 'Tombstone' "$input"
figlet -f 'Trek' "$input"
figlet -f 'Tsalagi' "$input"
figlet -f 'Tubular' "$input"
figlet -f 'Two Point' "$input"
figlet -f 'USA Flag' "$input"
figlet -f 'Univers' "$input"
figlet -f 'Wavy' "$input"
figlet -f 'Weird' "$input"
figlet -f 'Whimsy' "$input";echo
else echo;exit 1
fi
fi
fi
}

#>.........................................

trap '' 2
t-banner
reqirements
options
trap 5

#>.........................................
